{% set name = "kennard-stone" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kennard_stone-{{ version }}.tar.gz
  sha256: cbd8c9a514762b4943d0f22e74fbe28500a67478ddeeae1e316ef99d8dd473eb

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy >=1.20.0
    - scikit-learn
    - typing_extensions >=4.9.0

test:
  imports:
    - kennard_stone
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A method for selecting samples by spreading the training data evenly.
  dev_url: https://github.com/yu9824/kennard_stone
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yu9824
