{% set name = "kennard-stone" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kennard_stone-{{ version }}.tar.gz
  sha256: 911ba6404fa305609dd7fcb180e220bfde8bf0653bc3538fefb708f4205cc9ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scikit-learn

test:
  imports:
    - kennard_stone
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yu9824/kennard_stone
  summary: A method for selecting samples by spreading the training data evenly.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yu9824
