{% set name = "kennard-stone" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kennard_stone-{{ version }}.tar.gz
  sha256: 0bc9c11e118a40c4e4eec6536a0df789e21105e9f0c312796322590dc2f252c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.20.0
    - scikit-learn

test:
  imports:
    - kennard_stone
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yu9824/kennard-stone
  summary: '"A method for selecting samples by spreading the training data evenly."'
  dev_url: https://github.com/yu9824/kennard-stone
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yu9824
