{% set name = "kennard-stone" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kennard_stone-{{ version }}.tar.gz
  sha256: 13c92c8c76efa6a6129a8f190b62f2864f5485f09ada2f62d1c5d18b49838c95

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scikit-learn

test:
  imports:
    - kennard_stone
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yu9824/kennard_stone
  summary: A method for selecting samples by spreading the training data evenly.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yu9824
