{% set name = "kennard-stone" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kennard_stone-{{ version }}.tar.gz
  sha256: 2eb59131027f7cc8d3bc61bdfe0fe86b6d501b2c9d1d8452fc16879fbcd9af90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scikit-learn

test:
  imports:
    - kennard_stone
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yu9824/kennard_stone
  summary: A method for selecting samples by spreading the training data evenly.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yu9824
